coverage:
  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: auto           # specify the target coverage for each commit status
                               #   option: "auto" (must increase from parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit
        threshold: 0.1%        # allowed to drop X% and still result in a "success" commit status
        if_not_found: success  # if parent is not found report status as success, error, or failure

    patch:                     # pull requests only: this commit status will measure the
                               # entire pull requests Coverage Diff. Checking if the lines
                               # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        threshold: 0.1%          # allowed to drop X% and still result in a "success" commit status
        if_not_found: success